[package]
name = "some-splatoon-api-client-on-rust"
version = "0.1.0"
authors = ["Arata Tanaka <tarata43@yahoo.co.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
